### ISSUE TITLE
The problems I encountered.

### ISSUE THREAD

**Issue by juezhihe** [fakekey/orbwalk#1]
When I deploy the code generation, I am missing "pyconfig.h". Can you help me deploy the code correctly?

**Comment by fakekey** [comment]
You need [python3.10.10](https://www.python.org/downloads/release/python-31010/) and boost python installed, you could reference [Here](https://github.com/ImbaMDT/LViewPlus64).
They used python3.9.0, so make sure change everything to 3.10.10 because mine used 3.10.10.
